enum LoginErrorEnum {
  INVALID_DATA = "INVALID_DATA",
  EMAIL_NOT_CONFIRMED = "EMAIL_NOT_CONFIRMED",
  USER_BLOCKED = "USER_BLOCKED",
  PASSWORD_NOT_SET = "PASSWORD_NOT_SET",
}

export default LoginErrorEnum;
