name: Test SSH Connection

on:
  workflow_dispatch:  # Manual trigger
  push:
    branches: [ git_actions ]

jobs:
  test-ssh:
    runs-on: self-hosted

    steps:
      # CI

      # 1. Checkout code
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22' # or your preferred version

      # 3. Install dependencies
      - name: Install dependencies
        run: npm i

      # 4. Build production code
      - name: Build production bundle
        run: npm run build
        env:
          NODE_ENV: production

      # CD

      # 5. Copy files to deployment directory
      - name: Prepare deployment
        run: |
          DEPLOY_DIR="/var/www/www-root/data/www/prod-api.my-places.by"
          
          # Copy necessary files
          cp -R dist/ $DEPLOY_DIR/
          cp package.json package-lock.json $DEPLOY_DIR/
          cp -R public/ $DEPLOY_DIR/  # If you have public folder
          cp tsconfig*.json nest-cli.json $DEPLOY_DIR/  # Config files

      # 6. Restart application
      - name: Restart application
        run: |
          # Using PM2 (install first: npm install -g pm2)
          pm2 restart prod-api.my-places.by || \
          pm2 start npm --name "prod-api.my-places.by" -- start --prefix /var/www/www-root/data/www/prod-api.my-places.by    


#      - name: Test SSH Connection to GitHub
#        run: ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_ed25519 user@my-places.by "touch ~/1"